# Generated by Django 3.1 on 2020-09-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Not Set', max_length=50, verbose_name='display_name'),
        ),
    ]
