# Generated by Django 3.0.8 on 2020-08-03 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog_post_image',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='blog_site.Blog_Post'),
        ),
    ]
