# Generated by Django 3.1 on 2020-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_auto_20200802_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='isMainPost',
            field=models.BooleanField(default=True),
        ),
    ]
