# Generated by Django 3.1 on 2020-08-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_blog_post_ismainpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
