# Generated by Django 3.1 on 2020-09-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0005_blog_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post_comments',
            old_name='post',
            new_name='blog_post',
        ),
    ]
