# Generated by Django 3.1 on 2020-09-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_auto_20200903_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post_comments',
            name='reply',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_site.blog_post_comments'),
        ),
        migrations.AlterField(
            model_name='blog_post_comments',
            name='comment',
            field=models.TextField(default='', max_length=250),
        ),
    ]
