# Generated by Django 3.1 on 2020-09-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0007_welcomemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
