# Generated by Django 3.1 on 2020-09-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0015_auto_20200903_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post_comments',
            old_name='reply',
            new_name='parent',
        ),
    ]
