# Generated by Django 3.1 on 2020-09-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0017_auto_20200903_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post_comments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog_site.blog_post_comments'),
        ),
    ]
