# Generated by Django 3.1 on 2020-09-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0020_remove_blog_post_comments_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post_comments',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
