# Generated by Django 3.1 on 2020-09-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0021_blog_post_comments_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post_Comment_Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='blog_post_comments',
            name='votes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blog_post_comment_votes'),
        ),
    ]
