# Generated by Django 3.1 on 2020-09-08 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0023_blog_post_comment_votes_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post_Comment_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_post_comments',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Blog_Post_Comment_Votes',
        ),
        migrations.AddField(
            model_name='blog_post_comment_vote',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.blog_post_comments'),
        ),
        migrations.AddField(
            model_name='blog_post_comment_vote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
