# Generated by Django 3.1 on 2020-09-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0025_auto_20200908_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post_comment_vote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
