# Generated by Django 3.1 on 2020-09-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0026_auto_20200908_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
